/*
 * Copyright (c) 2026 Hunan OpenValley Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// arktsid: splice_negative_start_removes_element
// description: Array.prototype.splice - 'from' is the result of ToString(actualStart+k) in an Array

function main(): void {
    let arrObj: int[] = [1, 2, 3];
    let newArrObj: int[] = arrObj.splice(-2, 1);
    arktest.assertEQ(newArrObj.length, 1, 'newArrObj.length');
    arktest.assertEQ(newArrObj[0], 2, 'newArrObj[0]');
}