/*
 * Copyright (c) 2025 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

@Entry
@Component
struct UIComponentListCapability007 {
  @State numbers: number[] = [];
  @State columnsGap: number = 10;
  @State rowsGap: number = 10;
  private scroller: Scroller = new Scroller();
  private caseName: string = 'SUB_ACE_UI_COMPONENT_LISTANDGRID_LIST_CAPABILITY_0110';

  aboutToAppear(): void {
    for(let i: number = 0; i < 20; i++) {
      this.numbers.push(i);
    }
  }

  build() {
    Column() {
      List({ scroller: this.scroller, space: 10 }) {
        ListItem() {
          Text('宽设置500 高设置300 设置aspectRatio为0.5')
            .width('100%')
            .height('20%')
            .textAlign(TextAlign.Center)
            .fontStyle(FontStyle.Normal)
        }.backgroundColor(0xF9CF93)
        ForEach(this.numbers, (item: number) => {
          ListItem() {
            Text('item' + item)
              .width('100%')
              .height('20%')
              .textAlign(TextAlign.Center)
              .fontStyle(FontStyle.Normal)
          }.backgroundColor(0xF9CF93)
        }, (item: string) => item)
      }
      .width(500)
      .height(300)
      .aspectRatio(0.5)
      .border({ width: 3, color: Color.Red })
      .scrollBarColor(Color.Gray)
      .enableScrollInteraction(true)
      .multiSelectable(false)
      .edgeEffect(EdgeEffect.Spring)
      .scrollBar(BarState.On)
      .scrollBarWidth(10)
      .backgroundColor(0xFAEEE0)
    }
    .width('100%')
    .height('100%')
  }
}