/**
 * Copyright (c) 2025 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { image } from '@kit.ImageKit';

@Entry
@Component
struct BuilderDemo650 {
  @Builder
  showTextBuilder() {
    Text('linearGradient').fontSize(12).width('90%').fontColor(0xCCCCCC)
    Row()
      .width('90%')
      .height(50)
      .linearGradient({
        angle: 90,
        colors: [[0xff0000, 0.0], [0x0000ff, 0.3], [0xffff00, 1.0]]
      })
    Text('linearGradient Repeat').fontSize(12).width('90%').fontColor(0xCCCCCC)
    Row()
      .width('90%')
      .height(50)
      .linearGradient({
        direction: GradientDirection.Left, // 渐变方向
        repeating: true, // 渐变颜色是否重复
        colors: [[0xff0000, 0.0], [0x0000ff, 0.3], [0xffff00, 0.5]] // 数组末尾元素占比小于1时满足重复着色效果
      })
  }
  build() {
    Column() {
      // 无参数
      this.showTextBuilder()
    }
  }
}
