/*
 * Copyright (c) 2026 Hunan OpenValley Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// arktsid: identifier_values_russian_lowercase_unicode_codepoint
// description: Russian lowercase identifiers can use Unicode code point escapes

function main(): void {
    let \u{430}: int = 1;
    arktest.assertEQ(а, 1);
    let \u{431}: int = 1;
    arktest.assertEQ(б, 1);
    let \u{432}: int = 1;
    arktest.assertEQ(в, 1);
    let \u{433}: int = 1;
    arktest.assertEQ(г, 1);
    let \u{434}: int = 1;
    arktest.assertEQ(д, 1);
    let \u{435}: int = 1;
    arktest.assertEQ(е, 1);
    let \u{436}: int = 1;
    arktest.assertEQ(ж, 1);
    let \u{437}: int = 1;
    arktest.assertEQ(з, 1);
    let \u{438}: int = 1;
    arktest.assertEQ(и, 1);
    let \u{439}: int = 1;
    arktest.assertEQ(й, 1);
    let \u{43A}: int = 1;
    arktest.assertEQ(к, 1);
    let \u{43B}: int = 1;
    arktest.assertEQ(л, 1);
    let \u{43C}: int = 1;
    arktest.assertEQ(м, 1);
    let \u{43D}: int = 1;
    arktest.assertEQ(н, 1);
    let \u{43E}: int = 1;
    arktest.assertEQ(о, 1);
    let \u{43F}: int = 1;
    arktest.assertEQ(п, 1);
    let \u{440}: int = 1;
    arktest.assertEQ(р, 1);
    let \u{441}: int = 1;
    arktest.assertEQ(с, 1);
    let \u{442}: int = 1;
    arktest.assertEQ(т, 1);
    let \u{443}: int = 1;
    arktest.assertEQ(у, 1);
    let \u{444}: int = 1;
    arktest.assertEQ(ф, 1);
    let \u{445}: int = 1;
    arktest.assertEQ(х, 1);
    let \u{446}: int = 1;
    arktest.assertEQ(ц, 1);
    let \u{447}: int = 1;
    arktest.assertEQ(ч, 1);
    let \u{448}: int = 1;
    arktest.assertEQ(ш, 1);
    let \u{449}: int = 1;
    arktest.assertEQ(щ, 1);
    let \u{44A}: int = 1;
    arktest.assertEQ(ъ, 1);
    let \u{44B}: int = 1;
    arktest.assertEQ(ы, 1);
    let \u{44C}: int = 1;
    arktest.assertEQ(ь, 1);
    let \u{44D}: int = 1;
    arktest.assertEQ(э, 1);
    let \u{44E}: int = 1;
    arktest.assertEQ(ю, 1);
    let \u{44F}: int = 1;
    arktest.assertEQ(я, 1);
    let \u{451}: int = 1;
    arktest.assertEQ(ё, 1);
}
