/*
 * Copyright (c) 2026 Hunan OpenValley Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*---
desc: non-int array index rejected at compile - string primitive as array index
tags: [compile-only, negative]
expected_out_1: |-
    Semantic error ESE0127: No matching indexing signature for $_set("0", Int)
    Semantic error ESE0251: Cannot find index access method with the required signature.
    Semantic error ESE0046: Type '"0"' is not compatible with type 'Int' at index 1
    Semantic error ESE0127: No matching indexing signature for $_set("1", Int)
    Semantic error ESE0046: Type '"1"' is not compatible with type 'Int' at index 1
---*/

function main(): void {
    let x: int[] = [0, 1, 2, 3];
    x['0'] = 0;
    let y: int[] = [0, 1, 2, 3];
    y['1'] = 1;
}
