/**
 * Copyright (c) 2025 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { describe, beforeAll, beforeEach, afterEach, afterAll, it, expect, Level } from '@ohos/hypium';
import { BusinessError, commonEventManager } from '@kit.BasicServicesKit';
import { Driver, ON ,Component, UiWindow } from '@kit.TestKit';
import { uiAppearance } from '@kit.ArkUI';
import Settings from '../model/Settings';
import windowSnap from '../model/snapShot';
import Logger from '../model/Logger';
import Utils from '../model/Utils';


let TAG = 'RunTimeTest';

function sleep(ms: number) {
  return new Promise<string>(resolve => setTimeout(resolve, ms));
}

export default function UIComponentListAndGridModifier() {
  describe('UIComponentListAndGridModifier', () => {
    beforeAll(() => {

    })
    beforeEach(() => {

    })

    afterEach(async (done: Function) => {
      if (Settings.windowClass == undefined) {
        return
      }
      Settings.windowClass.destroyWindow((err) => {
        if (err.code) {
          Logger.error(`[${TAG}_afterEach]`, `Failed to destroy the window. Cause : ${JSON.stringify(err)}`);
          return;
        }
        Logger.info(`[${TAG}_afterEach]`, `Succeeded in destroy the window.`);
      })
      await Utils.sleep(1000);
      done();
    })

    afterAll(() => {

    })

    
    /*
     * @tc.number  SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0010
     * @tc.name    SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0010
     * @tc.desc    Set swipeAction via modifier test
     * @tc.level   3
     */
    it('SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0010', Level.LEVEL3, async (done: Function) => {
      TAG = 'SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0010';
      let pageName = "UIComponentListAndGridModifier0010";
      Logger.info(`[${TAG}]`, `Case start.`);
      Settings.createWindow('testability/pages/UIComponentListAndGridModifier/' + pageName);
      let driver: Driver = Driver.create();
      let button: Component = await driver.waitForComponent(ON.id(pageName + '_01'), 1000);
      let targetComponent: Component = await driver.waitForComponent(ON.id(pageName + '_02'), 1000);
      let item: Component = await driver.waitForComponent(ON.id(pageName + '_02_1'), 1000);
      let itemCenter = await item.getBoundsCenter();
      let itemBounds = await item.getBounds();
      let center = await targetComponent.getBoundsCenter();
      let bounds = await targetComponent.getBounds();
      await driver.waitForIdle(1000, 2000);
      await driver.swipe(itemBounds.right - 50, itemCenter.y, itemBounds.left + 50, itemCenter.y, 1000);
      await driver.waitForIdle(1000, 2000);
      await windowSnap.snapShot();
      await Utils.sleep(1000);
      Logger.info(`[${TAG}]`, `Case finish.`);
      done();
    })

    /*
     * @tc.number  SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0150
     * @tc.name    SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0150
     * @tc.desc    List component dynamically change sticky declared with @state test
     * @tc.level   3
     */
    it('SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0150', Level.LEVEL3, async (done: Function) => {
      TAG = 'SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0150';
      let pageName = "UIComponentListAndGridModifier0150";
      Logger.info(`[${TAG}]`, `Case start.`);
      Settings.createWindow('testability/pages/UIComponentListAndGridModifier/' + pageName);
      let driver: Driver = Driver.create();
      // let button: Component = await driver.waitForComponent(ON.id(pageName + '_01'), 1000);
      // let targetComponent: Component = await driver.waitForComponent(ON.id(pageName + '_02'), 1000);
      // let item: Component = await driver.waitForComponent(ON.id(pageName + '_02_1'), 1000);
      // let itemCenter = await item.getBoundsCenter();
      // let itemBounds = await item.getBounds();
      // let center = await targetComponent.getBoundsCenter();
      // let bounds = await targetComponent.getBounds();
      // await driver.waitForIdle(1000, 2000);
      // await driver.swipe(itemBounds.right - 50, itemCenter.y, itemBounds.left + 50, itemCenter.y, 1000);
      // await driver.waitForIdle(1000, 2000);
      // await windowSnap.snapShot();
      // await Utils.sleep(1000);
      // Logger.info(`[${TAG}]`, `Case finish.`);
      // done();
    })

    /*
     * @tc.number  SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0370
     * @tc.name    SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0370
     * @tc.desc    List component dynamically change enableScrollInteraction declared with @state test
     * @tc.level   3
     */
    it('SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0370', Level.LEVEL3, async (done: Function) => {
      TAG = 'SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0370';
      let pageName = "UIComponentListAndGridModifier0370";
      Logger.info(`[${TAG}]`, `Case start.`);
      Settings.createWindow('testability/pages/UIComponentListAndGridModifier/' + pageName);
      let driver: Driver = Driver.create();
      let button: Component = await driver.waitForComponent(ON.id(pageName + '_01'), 1000);
      let targetComponent: Component = await driver.waitForComponent(ON.id(pageName + '_02'), 1000);
      let item: Component = await driver.waitForComponent(ON.id(pageName + '_02_1'), 1000);
      let itemCenter = await item.getBoundsCenter();
      let itemBounds = await item.getBounds();
      let center = await targetComponent.getBoundsCenter();
      let bounds = await targetComponent.getBounds();
      await driver.waitForIdle(1000, 2000);
      await driver.swipe(itemBounds.right - 50, itemCenter.y, itemBounds.left + 50, itemCenter.y, 1000);
      await driver.waitForIdle(1000, 2000);
      await windowSnap.snapShot();
      await Utils.sleep(1000);
      Logger.info(`[${TAG}]`, `Case finish.`);
      done();
    })

    /*
     * @tc.number  SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0450
     * @tc.name    SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0450
     * @tc.desc    Dynamically change chainAnimation declared with @state test
     * @tc.level   3
     */
    it('SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0450', Level.LEVEL3, async (done: Function) => {
      TAG = 'SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0450';
      let pageName = "UIComponentListAndGridModifier0450";
      Logger.info(`[${TAG}]`, `Case start.`);
      Settings.createWindow('testability/pages/UIComponentListAndGridModifier/' + pageName);
      let driver: Driver = Driver.create();
      let button: Component = await driver.waitForComponent(ON.id(pageName + '_01'), 1000);
      let targetComponent: Component = await driver.waitForComponent(ON.id(pageName + '_02'), 1000);
      let item: Component = await driver.waitForComponent(ON.id(pageName + '_02_1'), 1000);
      let itemCenter = await item.getBoundsCenter();
      let itemBounds = await item.getBounds();
      let center = await targetComponent.getBoundsCenter();
      let bounds = await targetComponent.getBounds();
      await driver.waitForIdle(1000, 2000);
      await driver.swipe(itemBounds.right - 50, itemCenter.y, itemBounds.left + 50, itemCenter.y, 1000);
      await driver.waitForIdle(1000, 2000);
      await windowSnap.snapShot();
      await Utils.sleep(1000);
      Logger.info(`[${TAG}]`, `Case finish.`);
      done();
    })

    /*
     * @tc.number  SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0540
     * @tc.name    SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0540
     * @tc.desc    Set multiSelectable to true via modifier test
     * @tc.level   3
     */
    it('SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0540', Level.LEVEL3, async (done: Function) => {
      TAG = 'SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0540';
      let pageName = "UIComponentListAndGridModifier0540";
      Logger.info(`[${TAG}]`, `Case start.`);
      Settings.createWindow('testability/pages/UIComponentListAndGridModifier/' + pageName);
      let driver: Driver = Driver.create();
      let button: Component = await driver.waitForComponent(ON.id(pageName + '_01'), 1000);
      let targetComponent: Component = await driver.waitForComponent(ON.id(pageName + '_02'), 1000);
      let item: Component = await driver.waitForComponent(ON.id(pageName + '_02_1'), 1000);
      let itemCenter = await item.getBoundsCenter();
      let itemBounds = await item.getBounds();
      let center = await targetComponent.getBoundsCenter();
      let bounds = await targetComponent.getBounds();
      await driver.waitForIdle(1000, 2000);
      await driver.swipe(itemBounds.right - 50, itemCenter.y, itemBounds.left + 50, itemCenter.y, 1000);
      await driver.waitForIdle(1000, 2000);
      await windowSnap.snapShot();
      await Utils.sleep(1000);
      Logger.info(`[${TAG}]`, `Case finish.`);
      done();
    })

    /*
     * @tc.number  SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0550
     * @tc.name    SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0550
     * @tc.desc    Set multiSelectable to false via modifier test
     * @tc.level   3
     */
    it('SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0550', Level.LEVEL3, async (done: Function) => {
      TAG = 'SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0550';
      let pageName = "UIComponentListAndGridModifier0550";
      Logger.info(`[${TAG}]`, `Case start.`);
      Settings.createWindow('testability/pages/UIComponentListAndGridModifier/' + pageName);
      let driver: Driver = Driver.create();
      let button: Component = await driver.waitForComponent(ON.id(pageName + '_01'), 1000);
      let targetComponent: Component = await driver.waitForComponent(ON.id(pageName + '_02'), 1000);
      let item: Component = await driver.waitForComponent(ON.id(pageName + '_02_1'), 1000);
      let itemCenter = await item.getBoundsCenter();
      let itemBounds = await item.getBounds();
      let center = await targetComponent.getBoundsCenter();
      let bounds = await targetComponent.getBounds();
      await driver.waitForIdle(1000, 2000);
      await driver.swipe(itemBounds.right - 50, itemCenter.y, itemBounds.left + 50, itemCenter.y, 1000);
      await driver.waitForIdle(1000, 2000);
      await windowSnap.snapShot();
      await Utils.sleep(1000);
      Logger.info(`[${TAG}]`, `Case finish.`);
      done();
    })

    /*
     * @tc.number  SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0560
     * @tc.name    SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0560
     * @tc.desc    Set multiSelectable multiple times test
     * @tc.level   3
     */
    it('SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0560', Level.LEVEL3, async (done: Function) => {
      TAG = 'SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0560';
      let pageName = "UIComponentListAndGridModifier0560";
      Logger.info(`[${TAG}]`, `Case start.`);
      Settings.createWindow('testability/pages/UIComponentListAndGridModifier/' + pageName);
      let driver: Driver = Driver.create();
      let button: Component = await driver.waitForComponent(ON.id(pageName + '_01'), 1000);
      let targetComponent: Component = await driver.waitForComponent(ON.id(pageName + '_02'), 1000);
      let item: Component = await driver.waitForComponent(ON.id(pageName + '_02_1'), 1000);
      let itemCenter = await item.getBoundsCenter();
      let itemBounds = await item.getBounds();
      let center = await targetComponent.getBoundsCenter();
      let bounds = await targetComponent.getBounds();
      await driver.waitForIdle(1000, 2000);
      await driver.swipe(itemBounds.right - 50, itemCenter.y, itemBounds.left + 50, itemCenter.y, 1000);
      await driver.waitForIdle(1000, 2000);
      await windowSnap.snapShot();
      await Utils.sleep(1000);
      Logger.info(`[${TAG}]`, `Case finish.`);
      done();
    })

    /*
     * @tc.number  SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0570
     * @tc.name    SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0570
     * @tc.desc    Use one modifier to set multiSelectable for two components test
     * @tc.level   3
     */
    it('SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0570', Level.LEVEL3, async (done: Function) => {
      TAG = 'SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0570';
      let pageName = "UIComponentListAndGridModifier0570";
      Logger.info(`[${TAG}]`, `Case start.`);
      Settings.createWindow('testability/pages/UIComponentListAndGridModifier/' + pageName);
      let driver: Driver = Driver.create();
      let button: Component = await driver.waitForComponent(ON.id(pageName + '_01'), 1000);
      let targetComponent: Component = await driver.waitForComponent(ON.id(pageName + '_02'), 1000);
      let item: Component = await driver.waitForComponent(ON.id(pageName + '_02_1'), 1000);
      let itemCenter = await item.getBoundsCenter();
      let itemBounds = await item.getBounds();
      let center = await targetComponent.getBoundsCenter();
      let bounds = await targetComponent.getBounds();
      await driver.waitForIdle(1000, 2000);
      await driver.swipe(itemBounds.right - 50, itemCenter.y, itemBounds.left + 50, itemCenter.y, 1000);
      await driver.waitForIdle(1000, 2000);
      await windowSnap.snapShot();
      await Utils.sleep(1000);
      Logger.info(`[${TAG}]`, `Case finish.`);
      done();
    })

    /*
     * @tc.number  SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0590
     * @tc.name    SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0590
     * @tc.desc    Dynamically change enableScrollInteraction declared with @state test
     * @tc.level   3
     */
    it('SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0590', Level.LEVEL3, async (done: Function) => {
      TAG = 'SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0590';
      let pageName = "UIComponentListAndGridModifier0590";
      Logger.info(`[${TAG}]`, `Case start.`);
      Settings.createWindow('testability/pages/UIComponentListAndGridModifier/' + pageName);
      let driver: Driver = Driver.create();
      let button: Component = await driver.waitForComponent(ON.id(pageName + '_01'), 1000);
      let targetComponent: Component = await driver.waitForComponent(ON.id(pageName + '_02'), 1000);
      let item: Component = await driver.waitForComponent(ON.id(pageName + '_02_1'), 1000);
      let itemCenter = await item.getBoundsCenter();
      let itemBounds = await item.getBounds();
      let center = await targetComponent.getBoundsCenter();
      let bounds = await targetComponent.getBounds();
      await driver.waitForIdle(1000, 2000);
      await driver.swipe(itemBounds.right - 50, itemCenter.y, itemBounds.left + 50, itemCenter.y, 1000);
      await driver.waitForIdle(1000, 2000);
      await windowSnap.snapShot();
      await Utils.sleep(1000);
      Logger.info(`[${TAG}]`, `Case finish.`);
      done();
    })

    /*
     * @tc.number  SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0600
     * @tc.name    SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0600
     * @tc.desc    Add multiSelectable via attributeModifier test
     * @tc.level   3
     */
    it('SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0600', Level.LEVEL3, async (done: Function) => {
      TAG = 'SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0600';
      let pageName = "UIComponentListAndGridModifier0600";
      Logger.info(`[${TAG}]`, `Case start.`);
      Settings.createWindow('testability/pages/UIComponentListAndGridModifier/' + pageName);
      let driver: Driver = Driver.create();
      let button: Component = await driver.waitForComponent(ON.id(pageName + '_01'), 1000);
      let targetComponent: Component = await driver.waitForComponent(ON.id(pageName + '_02'), 1000);
      let item: Component = await driver.waitForComponent(ON.id(pageName + '_02_1'), 1000);
      let itemCenter = await item.getBoundsCenter();
      let itemBounds = await item.getBounds();
      let center = await targetComponent.getBoundsCenter();
      let bounds = await targetComponent.getBounds();
      await driver.waitForIdle(1000, 2000);
      await driver.swipe(itemBounds.right - 50, itemCenter.y, itemBounds.left + 50, itemCenter.y, 1000);
      await driver.waitForIdle(1000, 2000);
      await windowSnap.snapShot();
      await Utils.sleep(1000);
      Logger.info(`[${TAG}]`, `Case finish.`);
      done();
    })

    /*
     * @tc.number  SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0710
     * @tc.name    SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0710
     * @tc.desc    Dynamically change edgeEffect declared with @state test
     * @tc.level   3
     */
    it('SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0710', Level.LEVEL3, async (done: Function) => {
      TAG = 'SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_0710';
      let pageName = "UIComponentListAndGridModifier0710";
      Logger.info(`[${TAG}]`, `Case start.`);
      Settings.createWindow('testability/pages/UIComponentListAndGridModifier/' + pageName);
      let driver: Driver = Driver.create();
      let button: Component = await driver.waitForComponent(ON.id(pageName + '_01'), 1000);
      let targetComponent: Component = await driver.waitForComponent(ON.id(pageName + '_02'), 1000);
      let item: Component = await driver.waitForComponent(ON.id(pageName + '_02_1'), 1000);
      let itemCenter = await item.getBoundsCenter();
      let itemBounds = await item.getBounds();
      let center = await targetComponent.getBoundsCenter();
      let bounds = await targetComponent.getBounds();
      await driver.waitForIdle(1000, 2000);
      await driver.swipe(itemBounds.right - 50, itemCenter.y, itemBounds.left + 50, itemCenter.y, 1000);
      await driver.waitForIdle(1000, 2000);
      await windowSnap.snapShot();
      await Utils.sleep(1000);
      Logger.info(`[${TAG}]`, `Case finish.`);
      done();
    })

    /*
     * @tc.number  SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1000
     * @tc.name    SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1000
     * @tc.desc    WaterFlow set friction to 0.6 via modifier test
     * @tc.level   3
     */
    it('SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1000', Level.LEVEL3, async (done: Function) => {
      TAG = 'SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1000';
      let pageName = "UIComponentListAndGridModifier1000";
      Logger.info(`[${TAG}]`, `Case start.`);
      Settings.createWindow('testability/pages/UIComponentListAndGridModifier/' + pageName);
      let driver: Driver = Driver.create();
      let button: Component = await driver.waitForComponent(ON.id(pageName + '_01'), 1000);
      let targetComponent: Component = await driver.waitForComponent(ON.id(pageName + '_02'), 1000);
      let item: Component = await driver.waitForComponent(ON.id(pageName + '_02_1'), 1000);
      let itemCenter = await item.getBoundsCenter();
      let itemBounds = await item.getBounds();
      let center = await targetComponent.getBoundsCenter();
      let bounds = await targetComponent.getBounds();
      await driver.waitForIdle(1000, 2000);
      await driver.swipe(itemBounds.right - 50, itemCenter.y, itemBounds.left + 50, itemCenter.y, 1000);
      await driver.waitForIdle(1000, 2000);
      await windowSnap.snapShot();
      await Utils.sleep(1000);
      Logger.info(`[${TAG}]`, `Case finish.`);
      done();
    })

    /*
     * @tc.number  SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1010
     * @tc.name    SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1010
     * @tc.desc    WaterFlow set friction to 0 via modifier test
     * @tc.level   3
     */
    it('SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1010', Level.LEVEL3, async (done: Function) => {
      TAG = 'SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1010';
      let pageName = "UIComponentListAndGridModifier1010";
      Logger.info(`[${TAG}]`, `Case start.`);
      Settings.createWindow('testability/pages/UIComponentListAndGridModifier/' + pageName);
      let driver: Driver = Driver.create();
      let button: Component = await driver.waitForComponent(ON.id(pageName + '_01'), 1000);
      let targetComponent: Component = await driver.waitForComponent(ON.id(pageName + '_02'), 1000);
      let item: Component = await driver.waitForComponent(ON.id(pageName + '_02_1'), 1000);
      let itemCenter = await item.getBoundsCenter();
      let itemBounds = await item.getBounds();
      let center = await targetComponent.getBoundsCenter();
      let bounds = await targetComponent.getBounds();
      await driver.waitForIdle(1000, 2000);
      await driver.swipe(itemBounds.right - 50, itemCenter.y, itemBounds.left + 50, itemCenter.y, 1000);
      await driver.waitForIdle(1000, 2000);
      await windowSnap.snapShot();
      await Utils.sleep(1000);
      Logger.info(`[${TAG}]`, `Case finish.`);
      done();
    })

    /*
     * @tc.number  SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1020
     * @tc.name    SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1020
     * @tc.desc    WaterFlow set friction to -1 via modifier test
     * @tc.level   3
     */
    it('SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1020', Level.LEVEL3, async (done: Function) => {
      TAG = 'SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1020';
      let pageName = "UIComponentListAndGridModifier1020";
      Logger.info(`[${TAG}]`, `Case start.`);
      Settings.createWindow('testability/pages/UIComponentListAndGridModifier/' + pageName);
      let driver: Driver = Driver.create();
      let button: Component = await driver.waitForComponent(ON.id(pageName + '_01'), 1000);
      let targetComponent: Component = await driver.waitForComponent(ON.id(pageName + '_02'), 1000);
      let item: Component = await driver.waitForComponent(ON.id(pageName + '_02_1'), 1000);
      let itemCenter = await item.getBoundsCenter();
      let itemBounds = await item.getBounds();
      let center = await targetComponent.getBoundsCenter();
      let bounds = await targetComponent.getBounds();
      await driver.waitForIdle(1000, 2000);
      await driver.swipe(itemBounds.right - 50, itemCenter.y, itemBounds.left + 50, itemCenter.y, 1000);
      await driver.waitForIdle(1000, 2000);
      await windowSnap.snapShot();
      await Utils.sleep(1000);
      Logger.info(`[${TAG}]`, `Case finish.`);
      done();
    })

    /*
     * @tc.number  SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1030
     * @tc.name    SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1030
     * @tc.desc    WaterFlow set friction to $r(0.6) via modifier test
     * @tc.level   3
     */
    it('SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1030', Level.LEVEL3, async (done: Function) => {
      TAG = 'SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1030';
      let pageName = "UIComponentListAndGridModifier1030";
      Logger.info(`[${TAG}]`, `Case start.`);
      Settings.createWindow('testability/pages/UIComponentListAndGridModifier/' + pageName);
      let driver: Driver = Driver.create();
      let button: Component = await driver.waitForComponent(ON.id(pageName + '_01'), 1000);
      let targetComponent: Component = await driver.waitForComponent(ON.id(pageName + '_02'), 1000);
      let item: Component = await driver.waitForComponent(ON.id(pageName + '_02_1'), 1000);
      let itemCenter = await item.getBoundsCenter();
      let itemBounds = await item.getBounds();
      let center = await targetComponent.getBoundsCenter();
      let bounds = await targetComponent.getBounds();
      await driver.waitForIdle(1000, 2000);
      await driver.swipe(itemBounds.right - 50, itemCenter.y, itemBounds.left + 50, itemCenter.y, 1000);
      await driver.waitForIdle(1000, 2000);
      await windowSnap.snapShot();
      await Utils.sleep(1000);
      Logger.info(`[${TAG}]`, `Case finish.`);
      done();
    })

    /*
     * @tc.number  SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1060
     * @tc.name    SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1060
     * @tc.desc    WaterFlow add friction via attributeModifier test
     * @tc.level   3
     */
    it('SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1060', Level.LEVEL3, async (done: Function) => {
      TAG = 'SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1060';
      let pageName = "UIComponentListAndGridModifier1060";
      Logger.info(`[${TAG}]`, `Case start.`);
      Settings.createWindow('testability/pages/UIComponentListAndGridModifier/' + pageName);
      let driver: Driver = Driver.create();
      let button: Component = await driver.waitForComponent(ON.id(pageName + '_01'), 1000);
      let targetComponent: Component = await driver.waitForComponent(ON.id(pageName + '_02'), 1000);
      let item: Component = await driver.waitForComponent(ON.id(pageName + '_02_1'), 1000);
      let itemCenter = await item.getBoundsCenter();
      let itemBounds = await item.getBounds();
      let center = await targetComponent.getBoundsCenter();
      let bounds = await targetComponent.getBounds();
      await driver.waitForIdle(1000, 2000);
      await driver.swipe(itemBounds.right - 50, itemCenter.y, itemBounds.left + 50, itemCenter.y, 1000);
      await driver.waitForIdle(1000, 2000);
      await windowSnap.snapShot();
      await Utils.sleep(1000);
      Logger.info(`[${TAG}]`, `Case finish.`);
      done();
    })

    /*
     * @tc.number  SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1120
     * @tc.name    SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1120
     * @tc.desc    WaterFlow component dynamically change enableScrollInteraction declared with @state test
     * @tc.level   3
     */
    it('SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1120', Level.LEVEL3, async (done: Function) => {
      TAG = 'SUB_ACE_UI_COMPONENT_LISTANDGRID_MODIFIER_1120';
      let pageName = "UIComponentListAndGridModifier1120";
      Logger.info(`[${TAG}]`, `Case start.`);
      Settings.createWindow('testability/pages/UIComponentListAndGridModifier/' + pageName);
      let driver: Driver = Driver.create();
      let button: Component = await driver.waitForComponent(ON.id(pageName + '_01'), 1000);
      let targetComponent: Component = await driver.waitForComponent(ON.id(pageName + '_02'), 1000);
      let item: Component = await driver.waitForComponent(ON.id(pageName + '_02_1'), 1000);
      let itemCenter = await item.getBoundsCenter();
      let itemBounds = await item.getBounds();
      let center = await targetComponent.getBoundsCenter();
      let bounds = await targetComponent.getBounds();
      await driver.waitForIdle(1000, 2000);
      await driver.swipe(itemBounds.right - 50, itemCenter.y, itemBounds.left + 50, itemCenter.y, 1000);
      await driver.waitForIdle(1000, 2000);
      await windowSnap.snapShot();
      await Utils.sleep(1000);
      Logger.info(`[${TAG}]`, `Case finish.`);
      done();
    })

  })
}
