/**
 * Copyright (c) 2026 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { afterEach, describe, it, Level } from '@ohos/hypium'
import Settings from '../model/Settings'
import Logger from '../model/Logger'
import Utils from '../model/Utils'
import { Driver, ON } from '@kit.TestKit'
import windowSnap from '../model/snapShot'

export default function UiComponentMediaImageInteraction0010() {
  describe('UiComponentMediaImageInteraction0010', () => {
    afterEach(async (done: Function) => {
      if (Settings.windowClass == undefined) {
        done()
        return
      }
      Settings.windowClass.destroyWindow((err) => {
        if (err.code) {
          Logger.error('TEST', `Failed to destroy the window.Cause :${JSON.stringify(err)}`)
          return;
        }
        Logger.info('TEST', `Succeeded in destroy the window`);
      })
      await Utils.sleep(500);
      done()
    })

    /*
     * @tc.number : SUB_ACE_UI_COMPONENT_MEDIA_IMAGE_INTERACTION_0010
     * @tc.name   : MEDIA IMAGE INTERACTION 0010
     * @tc.desc   : Verify visual interaction path for SUB_ACE_UI_COMPONENT_MEDIA_IMAGE_INTERACTION_0010: 长按图片，可以将其选择的图片拖入另一图片框中，在另一图片框中显示该图片。.
     * @tc.type   : Function
     * @tc.size   : MediumTest
     * @tc.level  : 3
     */
    it('SUB_ACE_UI_COMPONENT_MEDIA_IMAGE_INTERACTION_0010', Level.LEVEL3, async (done: Function) => {
      Settings.createWindow('testability/pages/UiComponentMediaImageInteraction/UiComponentMediaImageInteraction0010')
      let driver = await Driver.create()
      await Utils.sleep(800)
      let target = await driver.waitForComponent(ON.id('image_interaction_0010'), 2000)
      await Utils.sleep(300)
      await windowSnap.snapShot('SUB_ACE_UI_COMPONENT_MEDIA_IMAGE_INTERACTION_0010_01')
      await Utils.sleep(1000)
      done()
    })
  })
}
